packages:
  - 'apps/*'
  - 'agents/*'
  - 'integrations/*'
  - 'sdk/*'
  - 'packages/*'
  - '!packages/design-system'
allowBuilds:
  '@swc/core': true
  esbuild: true
  onnxruntime-node: false
  protobufjs: true
  puppeteer: false
  sharp: true
