import type { GStackAgentDefinition, GStackGateRequirement } from './agentTypes';

export const GSTACK_GATE_REQUIREMENTS: readonly GStackGateRequirement[] = [
  {
    key: 'dns',
    label: 'DNS delegation',
    requiredProof: 'Registrar nameservers match Route 53 hosted zone NS records and api.devonn.ai resolves.',
    blocksShip: true,
  },
  {
    key: 'health',
    label: 'Backend health',
    requiredProof: 'curl https://api.devonn.ai/health returns HTTP 200 OK.',
    blocksShip: true,
  },
  {
    key: 'ci',
    label: 'GitHub Actions CI',
    requiredProof: 'All required GitHub Actions checks pass on the target commit.',
    blocksShip: true,
  },
  {
    key: 'sentry',
    label: 'Sentry clean',
    requiredProof: 'No new production error spike exists after deployment verification.',
    blocksShip: true,
  },
  {
    key: 'bundle',
    label: 'Bundle size',
    requiredProof: 'Production frontend bundle remains below 900KB gzip target.',
    blocksShip: true,
  },
  {
    key: 'hmac',
    label: 'Zero-Trust HMAC',
    requiredProof: 'Protected routes reject unsigned traffic and accept valid HMAC signatures.',
    blocksShip: true,
  },
  {
    key: 'hitl',
    label: 'Hermes HITL approval',
    requiredProof: 'Telegram/Hermes approval exists before destructive actions.',
    blocksShip: true,
  },
];

const shippingGates = ['dns', 'health', 'ci', 'sentry', 'bundle', 'hmac'] as const;
const destructiveActionBlockers = ['merge to main', 'delete data', 'run migration', 'rotate secrets', 'production deploy'] as const;

export const GSTACK_AGENT_REGISTRY: readonly GStackAgentDefinition[] = [
  {
    command: '/ceo',
    name: 'CEO',
    layer: 'strategic',
    role: 'Product vision and POL loop owner',
    devonnContext: 'DEVONN.AI ecosystem decisions, Echoes of the Door, Genesis Weave, HNF, and MoneyHub direction.',
    defaultInputs: ['business objective', 'current gate state', 'strategic constraints'],
    defaultOutputs: ['decision memo', 'priority order', 'success definition'],
    allowedActions: ['prioritize roadmap', 'approve strategy', 'define operating principles'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
  {
    command: '/plan',
    name: 'Planner',
    layer: 'strategic',
    role: 'RIPE spec writer',
    devonnContext: 'Turns vague intent into executable five-phase plans and GitHub issue-ready specs.',
    defaultInputs: ['operator intent', 'repo context', 'acceptance criteria'],
    defaultOutputs: ['implementation spec', 'task breakdown', 'issue body'],
    allowedActions: ['draft issues', 'write specs', 'define phases'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
  {
    command: '/office-hours',
    name: 'Office Hours',
    layer: 'strategic',
    role: 'Idea pressure-test partner',
    devonnContext: 'Reviews new pillars, HNF programs, MoneyHub affiliate strategy, and product-market risks.',
    defaultInputs: ['raw idea', 'target user', 'constraints'],
    defaultOutputs: ['risk map', 'opportunity map', 'next experiment'],
    allowedActions: ['challenge assumptions', 'suggest experiments', 'identify blind spots'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
  {
    command: '/eng-manager',
    name: 'Engineering Manager',
    layer: 'engineering',
    role: 'Architecture lock and technical sequencing',
    devonnContext: 'OpenClaw runtime, FastAPI, Supabase schema, Railway, and contract decisions.',
    defaultInputs: ['technical objective', 'current architecture', 'constraints'],
    defaultOutputs: ['architecture decision', 'dependency map', 'implementation order'],
    allowedActions: ['approve architecture', 'sequence work', 'define integration contracts'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'active',
  },
  {
    command: '/build',
    name: 'Builder',
    layer: 'engineering',
    role: 'Implementation agent',
    devonnContext: 'Creates feature branches and code changes for supreme-ai-deployment-hub.',
    defaultInputs: ['approved spec', 'target files', 'acceptance tests'],
    defaultOutputs: ['code patch', 'tests', 'implementation notes'],
    allowedActions: ['create additive code', 'write tests', 'prepare PR branch'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'active',
  },
  {
    command: '/pair-agent',
    name: 'Pair Agent',
    layer: 'engineering',
    role: 'Coding partner',
    devonnContext: 'Follows CLAUDE.md conventions while assisting with focused coding tasks.',
    defaultInputs: ['code snippet', 'error output', 'desired behavior'],
    defaultOutputs: ['patch suggestion', 'explanation', 'test suggestion'],
    allowedActions: ['debug', 'refactor non-destructively', 'explain code'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'active',
  },
  {
    command: '/plan-devex',
    name: 'Developer Experience Planner',
    layer: 'engineering',
    role: 'DX review',
    devonnContext: 'Improves developer experience for ION/CTRL dashboard and repo workflows.',
    defaultInputs: ['workflow pain point', 'developer path', 'repo scripts'],
    defaultOutputs: ['DX recommendations', 'script improvements', 'onboarding notes'],
    allowedActions: ['review scripts', 'improve docs', 'suggest automation'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
  {
    command: '/plan-eng',
    name: 'Engineering Planner',
    layer: 'engineering',
    role: 'Pre-change architecture reviewer',
    devonnContext: 'Reviews infrastructure and application changes before build starts.',
    defaultInputs: ['proposed change', 'risk profile', 'system map'],
    defaultOutputs: ['engineering plan', 'risk controls', 'rollback notes'],
    allowedActions: ['review architecture', 'define rollback', 'identify dependencies'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'active',
  },
  {
    command: '/designer',
    name: 'Designer',
    layer: 'design',
    role: 'UI/UX and AI-slop catcher',
    devonnContext: 'ION/CTRL cyberpunk terminal aesthetic with CTRL dominant shell and Matrix-inspired discipline.',
    defaultInputs: ['screen goal', 'brand constraints', 'component state'],
    defaultOutputs: ['UI critique', 'component guidance', 'copy/design improvements'],
    allowedActions: ['review UI', 'suggest component structure', 'tighten visual hierarchy'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['bundle'],
    status: 'active',
  },
  {
    command: '/plan-design',
    name: 'Design Planner',
    layer: 'design',
    role: 'Design review',
    devonnContext: 'Figma-to-code review and component consistency checks.',
    defaultInputs: ['design goal', 'component inventory', 'brand rules'],
    defaultOutputs: ['design plan', 'component checklist', 'accessibility notes'],
    allowedActions: ['review design system', 'map components', 'flag inconsistency'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['bundle'],
    status: 'active',
  },
  {
    command: '/ios-design-review',
    name: 'iOS Design Reviewer',
    layer: 'design',
    role: 'iOS interface review',
    devonnContext: 'OpenClaw iPhone IDE and mobile command surfaces.',
    defaultInputs: ['iOS screen', 'interaction goal', 'mobile constraints'],
    defaultOutputs: ['iOS design review', 'tap target notes', 'mobile polish list'],
    allowedActions: ['review mobile UX', 'suggest iOS polish', 'flag usability issues'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['bundle'],
    status: 'standby',
  },
  {
    command: '/qa',
    name: 'QA',
    layer: 'quality-security',
    role: 'Real browser QA and gate validation',
    devonnContext: 'Headless Chromium checks against api.devonn.ai and ION dashboard.',
    defaultInputs: ['target URL', 'test plan', 'expected proof'],
    defaultOutputs: ['QA report', 'failure evidence', 'gate recommendation'],
    allowedActions: ['run non-destructive QA', 'validate health endpoints', 'collect evidence'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['dns', 'health', 'ci'],
    status: 'active',
  },
  {
    command: '/ios-qa',
    name: 'iOS QA',
    layer: 'quality-security',
    role: 'iPhone IDE QA',
    devonnContext: 'Tests the OpenClaw iPhone IDE and mobile workflows.',
    defaultInputs: ['mobile build', 'test path', 'expected behavior'],
    defaultOutputs: ['iOS QA report', 'bug list', 'reproduction steps'],
    allowedActions: ['test mobile flows', 'capture reproduction', 'validate fixes'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'standby',
  },
  {
    command: '/ios-fix',
    name: 'iOS Fixer',
    layer: 'quality-security',
    role: 'iOS bug fix agent',
    devonnContext: 'Patches OpenClaw iPhone IDE bugs after QA reproduction exists.',
    defaultInputs: ['bug report', 'affected files', 'expected fix'],
    defaultOutputs: ['patch', 'test notes', 'risk note'],
    allowedActions: ['patch mobile bugs', 'add regression checks', 'document fix'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'standby',
  },
  {
    command: '/ios-clean',
    name: 'iOS Cleaner',
    layer: 'quality-security',
    role: 'iOS cleanup',
    devonnContext: 'Removes dead code and unused imports in mobile surfaces.',
    defaultInputs: ['target files', 'lint findings', 'cleanup scope'],
    defaultOutputs: ['cleanup patch', 'lint notes', 'risk note'],
    allowedActions: ['remove unused code', 'simplify imports', 'document cleanup'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'standby',
  },
  {
    command: '/ios-sync',
    name: 'iOS Sync',
    layer: 'quality-security',
    role: 'iOS/runtime sync',
    devonnContext: 'Keeps the iPhone IDE aligned with main OpenClaw runtime behavior.',
    defaultInputs: ['runtime behavior', 'mobile behavior', 'contract map'],
    defaultOutputs: ['sync plan', 'drift report', 'patch list'],
    allowedActions: ['compare behavior', 'flag drift', 'propose sync patch'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci'],
    status: 'standby',
  },
  {
    command: '/security',
    name: 'Security',
    layer: 'quality-security',
    role: 'OWASP and STRIDE reviewer',
    devonnContext: 'Zero-Trust/HMAC audit, Telegram HITL gate review, secret hygiene, and threat modeling.',
    defaultInputs: ['threat surface', 'auth design', 'target change'],
    defaultOutputs: ['security findings', 'STRIDE map', 'required mitigations'],
    allowedActions: ['audit code', 'threat model', 'verify non-secret config'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['hmac', 'ci', 'sentry'],
    status: 'active',
  },
  {
    command: '/investigate',
    name: 'Investigator',
    layer: 'quality-security',
    role: 'Debug deep dives',
    devonnContext: 'CI failures, DNS issues, Railway deploy errors, Sentry traces, and production blockers.',
    defaultInputs: ['symptom', 'logs', 'recent changes'],
    defaultOutputs: ['root cause hypothesis', 'evidence list', 'fix path'],
    allowedActions: ['analyze logs', 'compare configs', 'recommend fixes'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
  {
    command: '/release',
    name: 'Release',
    layer: 'shipping',
    role: 'PR ship and changelog owner',
    devonnContext: 'Railway deploy, Route 53 DNS gate, Sentry verification, and bundle budget enforcement.',
    defaultInputs: ['release candidate', 'changelog', 'gate evidence'],
    defaultOutputs: ['release notes', 'gate report', 'rollback plan'],
    allowedActions: ['prepare release notes', 'verify gates', 'recommend release readiness'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: shippingGates,
    status: 'active',
  },
  {
    command: '/ship',
    name: 'Ship',
    layer: 'shipping',
    role: 'Close issue and merge coordinator',
    devonnContext: 'Merges only after all required gates pass; never skips gate discipline.',
    defaultInputs: ['approved PR', 'gate evidence', 'rollback plan'],
    defaultOutputs: ['ship decision', 'merge checklist', 'post-ship monitoring plan'],
    allowedActions: ['evaluate merge readiness', 'close shipped issue', 'write handoff'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [...shippingGates, 'hitl'],
    status: 'active',
  },
  {
    command: '/plan-ceo-review',
    name: 'CEO Review Planner',
    layer: 'shipping',
    role: 'CEO sign-off preparation',
    devonnContext: 'Final review before production push or private beta approval.',
    defaultInputs: ['candidate release', 'business impact', 'gate evidence'],
    defaultOutputs: ['CEO review packet', 'approve/hold recommendation', 'risk summary'],
    allowedActions: ['prepare signoff packet', 'summarize risk', 'clarify decision'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: shippingGates,
    status: 'active',
  },
  {
    command: '/review',
    name: 'Reviewer',
    layer: 'shipping',
    role: 'Code and PR reviewer',
    devonnContext: 'Reviews PRs on wesship/supreme-ai-deployment-hub and related Wesship repositories.',
    defaultInputs: ['PR diff', 'acceptance criteria', 'gate status'],
    defaultOutputs: ['review findings', 'approval blockers', 'suggested patch'],
    allowedActions: ['review code', 'flag risks', 'recommend tests'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: ['ci', 'sentry'],
    status: 'active',
  },
  {
    command: '/retro',
    name: 'Retro',
    layer: 'shipping',
    role: 'Weekly retrospective',
    devonnContext: 'Tracks per-agent shipping streaks, test health, gate pass rates, and learning loops.',
    defaultInputs: ['completed work', 'failed gates', 'incident notes'],
    defaultOutputs: ['retro report', 'improvement actions', 'agent scorecard'],
    allowedActions: ['summarize outcomes', 'identify process fixes', 'update lessons'],
    blockedWithoutApproval: destructiveActionBlockers,
    requiredGates: [],
    status: 'active',
  },
];

export function getGStackAgent(command: string): GStackAgentDefinition | undefined {
  return GSTACK_AGENT_REGISTRY.find((agent) => agent.command === command.trim());
}

export function listGStackCommands(): readonly string[] {
  return GSTACK_AGENT_REGISTRY.map((agent) => agent.command);
}
