import type { CommandRegistry } from './types.js';

const c = (code: string, category: string, description: string, approvalLevel: 0|1|2|3, extra: Partial<{regulated:boolean;aliases:string[];conflictsWith:string[]}> = {}) => ({ code, category, description, approvalLevel, ...extra });

export const registry: CommandRegistry = {
  version: '1.2.0',
  commands: [
    c('PRIMETIME','project','Apply complete PRIMETIME project context.',0),
    c('PROJECT-SCAN','project','Review related modules, plans, workflows, and decisions.',0),
    c('PROJECT-STATUS','project','Show completed, active, blocked, and pending work.',0),
    c('PROJECT-GAP','project','Identify missing components and weak connections.',0),
    c('PROJECT-PRIORITY','project','Rank work by value, urgency, risk, and dependencies.',0),
    c('PROJECT-NEXT','project','Recommend the best next action.',0),
    c('PROJECT-ROADMAP','project','Create a phased implementation roadmap.',1),
    c('PROJECT-BUILD','project','Convert a request into an implementation-ready plan.',1),
    c('CRM-AUDIT','crm','Audit CRM architecture, data, and workflows.',0,{aliases:['CRM-REVIEW','AUDIT-CRM']}),
    c('CRM-PIPELINE','crm','Design or improve pipeline stages.',1),
    c('CRM-TASKS','crm','Design follow-up tasks and reminders.',1),
    c('CRM-APPOINTMENTS','crm','Design appointment and calendar workflows.',1),
    c('CRM-REPORTS','crm','Create production and conversion reporting.',1),
    c('CRM-RBAC','crm','Define role-based access controls.',2),
    c('RLS-AUDIT','security','Review row-level security policies.',2),
    c('TOP25','sales','Build and organize a Top 25 prospect workflow.',1),
    c('LEAD-GEN','sales','Generate lead-generation strategies.',1),
    c('LEAD-QUALIFY','sales','Create qualification questions and scoring.',1),
    c('LEAD-NURTURE','sales','Design approved follow-up sequences.',2),
    c('APPOINTMENT-SET','sales','Create appointment-setting workflows.',2),
    c('FOLLOWUP-PLAN','sales','Create structured follow-up plans.',1),
    c('REFERRAL-ENGINE','sales','Build a repeatable referral workflow.',1),
    c('CONVERSION-AUDIT','sales','Review conversion performance.',0),
    c('COMPLIANCE-CHECK','compliance','Review licensing, advertising, and documentation risk.',2,{regulated:true}),
    c('INSURANCE-COMPLIANCE','compliance','Review insurance-specific communications and workflows.',3,{regulated:true}),
    c('TCPA-CHECK','compliance','Review automated call and text consent concerns.',3,{regulated:true}),
    c('DNC-CHECK','compliance','Flag Do Not Call restrictions.',3,{regulated:true}),
    c('PRIVACY-CHECK','compliance','Review personal-data collection and use.',2,{regulated:true}),
    c('NO-MISREP','compliance','Check for misleading or unsupported claims.',3,{regulated:true}),
    c('DISCLOSURE-CHECK','compliance','Identify missing disclosures and assumptions.',3,{regulated:true}),
    c('RECORDKEEPING','compliance','Define records required for evidence and review.',2,{regulated:true}),
    c('HUMAN-APPROVAL','control','Require human approval before execution.',2),
    c('ESCALATE-LICENSED','control','Route regulated decisions to a licensed representative.',3,{regulated:true}),
    c('AGENT-DESIGN','agent','Design an AI agent and its operating boundaries.',1),
    c('AGENT-SOUL','agent','Define agent behavior and operating principles.',1),
    c('AGENT-TOOLS','agent','Define agent tools and permissions.',1),
    c('AGENT-MEMORY','agent','Design agent memory.',1),
    c('AGENT-WORKFLOW','agent','Map agent operational steps.',1),
    c('AGENT-GUARDRAILS','agent','Define prohibited actions and approval gates.',2),
    c('AGENT-TEST','agent','Create agent tests.',1),
    c('AGENT-SCORECARD','agent','Define agent performance measures.',1),
    c('AGENT-ROUTER','agent','Route work to the correct specialist agent.',1),
    c('N8N-BUILD','automation','Design an n8n workflow.',1),
    c('N8N-ERROR','automation','Add failure branches and recovery handling.',1),
    c('N8N-LOGGING','automation','Add execution and audit logs.',1),
    c('N8N-APPROVAL','automation','Add human approval steps.',2),
    c('SMS-SEQUENCE','messaging','Create a multistep SMS sequence.',2),
    c('EMAIL-SEQUENCE','messaging','Create an automated email sequence.',2),
    c('ARCHITECTURE','development','Design technical architecture.',1),
    c('ENV-CHECK','development','Review environment variables and secrets.',1),
    c('SECURITY-AUDIT','security','Review the system security posture.',2),
    c('TEST-BUILD','development','Create unit, integration, and end-to-end tests.',1),
    c('CI-CD','development','Create build, test, and deployment pipelines.',1),
    c('DEPLOYMENT','development','Create deployment configuration.',2),
    c('BACKUP-PLAN','security','Create backup and recovery procedures.',1),
    c('PRODUCTION-READY','development','Check production readiness.',1),
    c('KPI-BUILD','analytics','Define key performance indicators.',0),
    c('FUNNEL-METRICS','analytics','Measure movement across funnel stages.',0),
    c('TEAM-PERFORMANCE','analytics','Review team-level performance.',0),
    c('COST-MODEL','analytics','Estimate operating costs.',0),
    c('REVENUE-MODEL','analytics','Create a revenue projection.',0),
    c('BOTTLENECK','analysis','Find the largest operational constraint.',0),
    c('WEEKLY-REPORT','analytics','Create a weekly business report.',0),
    c('CONCEPT-READ','concept','Read a source and identify concepts and candidate relationships.',1),
    c('CONCEPT-IMPORT','concept','Import an external map into draft graph records.',2),
    c('CONCEPT-NORMALIZE','concept','Normalize names, aliases, types, and edge labels.',1),
    c('CONCEPT-DEDUPE','concept','Detect duplicate concepts and prepare merge candidates.',2),
    c('CONCEPT-SOURCE','concept','Attach source evidence and provenance.',1),
    c('CONCEPT-CONFIDENCE','concept','Calculate concept and relationship confidence.',1),
    c('CONCEPT-CLUSTER','concept','Detect concept communities and topic clusters.',1),
    c('CONCEPT-CENTRALITY','concept','Find structurally influential concepts.',1),
    c('CONCEPT-GAP','concept','Detect missing or weak connections.',1),
    c('CONCEPT-BRIDGE','concept','Generate and rank bridge concepts and questions.',1),
    c('CONCEPT-CONTRADICTION','concept','Identify conflicting claims and relationships.',2),
    c('CONCEPT-COMPARE','concept','Compare graph versions or knowledge domains.',1),
    c('CONCEPT-MERGE','concept','Merge approved concept maps.',2),
    c('CONCEPT-CANON','concept','Promote validated graph records to canonical status.',3),
    c('CONCEPT-TRACE','concept','Show concept provenance and version history.',0),
    c('CONCEPT-EXPORT','concept','Export approved graph data to visualization tools.',1),
    c('INFRANODUS-ANALYZE','concept','Run approved text-network structural analysis through InfraNodus.',2),
    c('HEPTABASE-REVIEW','concept','Send draft concepts to a human visual review workspace.',2),
    c('ALGOR-EXTRACT','concept','Extract educational concept structures from approved materials.',1),
    c('GRAPH-RAG-BUILD','concept','Build graph-grounded retrieval context.',2),
    c('TABLE','format','Return a table.',0,{conflictsWith:['JSON','YAML']}),
    c('JSON','format','Return JSON.',0,{conflictsWith:['TABLE','YAML']}),
    c('YAML','format','Return YAML.',0,{conflictsWith:['TABLE','JSON']}),
    c('MARKDOWN','format','Return clean Markdown.',0),
    c('TECHNICAL','format','Use engineering-level detail.',0,{conflictsWith:['BEGINNER']}),
    c('BEGINNER','format','Explain for a beginner.',0,{conflictsWith:['TECHNICAL']})
  ],
  masterCodes: {
    'PRIMETIME-360':['PROJECT-SCAN','PROJECT-STATUS','PROJECT-GAP','PROJECT-PRIORITY','COMPLIANCE-CHECK','SECURITY-AUDIT','PROJECT-NEXT'],
    'CRM-360':['CRM-AUDIT','CRM-PIPELINE','CRM-TASKS','CRM-APPOINTMENTS','CRM-REPORTS','CRM-RBAC','RLS-AUDIT','PRODUCTION-READY'],
    'AUTOMATION-360':['N8N-BUILD','AGENT-WORKFLOW','N8N-ERROR','N8N-LOGGING','N8N-APPROVAL','HUMAN-APPROVAL'],
    'COMPLIANCE-360':['INSURANCE-COMPLIANCE','TCPA-CHECK','DNC-CHECK','PRIVACY-CHECK','NO-MISREP','DISCLOSURE-CHECK','RECORDKEEPING','ESCALATE-LICENSED'],
    'AGENT-360':['AGENT-DESIGN','AGENT-SOUL','AGENT-TOOLS','AGENT-MEMORY','AGENT-WORKFLOW','AGENT-GUARDRAILS','AGENT-TEST','AGENT-SCORECARD'],
    'LEADS-360':['TOP25','LEAD-GEN','LEAD-QUALIFY','LEAD-NURTURE','APPOINTMENT-SET','FOLLOWUP-PLAN','REFERRAL-ENGINE','CONVERSION-AUDIT'],
    'DEPLOY-360':['ARCHITECTURE','ENV-CHECK','SECURITY-AUDIT','TEST-BUILD','CI-CD','DEPLOYMENT','BACKUP-PLAN','PRODUCTION-READY'],
    'BUSINESS-360':['KPI-BUILD','FUNNEL-METRICS','TEAM-PERFORMANCE','COST-MODEL','REVENUE-MODEL','BOTTLENECK','WEEKLY-REPORT','PROJECT-NEXT'],
    'CONCEPT-360':['CONCEPT-READ','CONCEPT-NORMALIZE','CONCEPT-DEDUPE','CONCEPT-SOURCE','CONCEPT-CLUSTER','CONCEPT-GAP','CONCEPT-BRIDGE','CONCEPT-CONFIDENCE','HUMAN-APPROVAL','CONCEPT-CANON']
  }
};
