"""
Stream Output
==============
Handles delivery of animated avatar video to clients via WebRTC,
HLS (HTTP Live Streaming), or direct file serving.
"""

import asyncio
import logging
import os
from pathlib import Path
from typing import AsyncGenerator, Optional

logger = logging.getLogger(__name__)


class StreamOutput:
    """Manages video stream delivery to clients."""

    def __init__(
        self,
        protocol: str = "webrtc",
        output_dir: str = "/tmp/avatar-output",
        buffer_ms: int = 200,
        max_fps: int = 25,
    ):
        self.protocol = protocol
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.buffer_ms = buffer_ms
        self.max_fps = max_fps

    async def serve_video(self, session_id: str, video_path: str) -> dict:
        """
        Serve a generated video file to the client.

        For the MVP, this returns a direct URL to the generated video.
        In production, this would set up a WebRTC peer connection or
        HLS segment delivery.

        Args:
            session_id: Session identifier
            video_path: Path to the generated video file

        Returns:
            Dictionary with streaming URL and metadata
        """
        if self.protocol == "webrtc":
            return await self._serve_webrtc(session_id, video_path)
        elif self.protocol == "hls":
            return await self._serve_hls(session_id, video_path)
        else:
            return await self._serve_direct(session_id, video_path)

    async def _serve_webrtc(self, session_id: str, video_path: str) -> dict:
        """
        Set up WebRTC streaming for the video.

        In production, this would:
        1. Create a WebRTC peer connection
        2. Encode video frames as RTP packets
        3. Stream to the connected client

        For MVP, we return a signaling endpoint URL.
        """
        return {
            "protocol": "webrtc",
            "signaling_url": f"/ws/avatar/{session_id}",
            "video_url": f"/output/{session_id}.mp4",
            "stun_servers": ["stun:stun.l.google.com:19302"],
            "status": "ready",
        }

    async def _serve_hls(self, session_id: str, video_path: str) -> dict:
        """
        Generate HLS segments from the video for adaptive streaming.

        In production, this would:
        1. Segment the video into .ts chunks
        2. Generate an .m3u8 playlist
        3. Serve via CDN-compatible endpoints
        """
        playlist_url = f"/hls/{session_id}/playlist.m3u8"

        return {
            "protocol": "hls",
            "playlist_url": playlist_url,
            "segment_duration": 2,
            "status": "ready",
        }

    async def _serve_direct(self, session_id: str, video_path: str) -> dict:
        """Serve video as a direct download/stream URL."""
        return {
            "protocol": "direct",
            "video_url": f"/output/{session_id}.mp4",
            "status": "ready",
        }

    async def stream_frames(
        self, video_path: str
    ) -> AsyncGenerator[bytes, None]:
        """
        Async generator that yields video frames for real-time streaming.

        This is used by the WebSocket endpoint to push frames to connected
        clients as they are generated by PersonaLive.
        """
        frame_interval = 1.0 / self.max_fps

        # In production, this would read frames from PersonaLive's
        # output buffer in real-time. For MVP, we read from a file.
        if not Path(video_path).exists():
            logger.warning("Video file not found: %s", video_path)
            return

        try:
            import av

            container = av.open(video_path)
            for frame in container.decode(video=0):
                # Convert frame to bytes (JPEG for efficiency)
                img = frame.to_image()
                buffer = bytearray()
                img.save(buffer, format="JPEG", quality=85)
                yield bytes(buffer)
                await asyncio.sleep(frame_interval)

        except ImportError:
            logger.warning("PyAV not installed — frame streaming unavailable")
            return
        except Exception as e:
            logger.error("Frame streaming error: %s", str(e))
            return

    def cleanup_session_output(self, session_id: str):
        """Remove generated output files for a closed session."""
        session_dir = self.output_dir / session_id
        if session_dir.exists():
            import shutil
            shutil.rmtree(session_dir, ignore_errors=True)
            logger.info("Cleaned up output for session %s", session_id)
