#!/bin/bash
set -e

echo "=== Branch Protection Enforcement Script ==="
echo "This script provides instructions for setting up required branch protections."
echo "These must be configured manually in GitHub Settings or via Terraform."
echo ""
echo "Required Settings for 'main' branch:"
echo "1. Require pull request reviews before merging (Minimum: 1)"
echo "2. Require status checks to pass before merging"
echo "3. Require branches to be up to date before merging"
echo "4. Do not allow bypassing the above settings"
echo "5. Restrict who can push to matching branches (Admin only)"
echo ""
echo "Required Status Checks:"
echo "- Unit Tests"
echo "- Typecheck & Lint"
echo "- Build and Push Backend + Frontend"
echo "- Analyze Bundle Size"
echo "- Validate Commit Messages"
echo "- Validate Terraform"
echo "- Security Scan"
echo ""
echo "Note: The Devonn.ai Production Repository Security and Configuration Best Practices"
echo "dictate that force pushes must be prevented and secret scanning must be enabled."
echo "==========================================="
