import React from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ArrowRight, Workflow, Users, HeartHandshake, FileText, LineChart, Headphones } from 'lucide-react';
import Footer from '@/components/Footer';

const workflows = [
  { icon: Users, title: 'Lead generation', body: 'Continuous prospect research, enrichment, and qualified outbound across channels.' },
  { icon: HeartHandshake, title: 'CRM automation', body: 'Auto-update records, log activity, and trigger follow-ups from any signal.' },
  { icon: FileText, title: 'Insurance workflows', body: 'Underwriting prep, claims triage, and document extraction with full audit trail.' },
  { icon: Headphones, title: 'Customer support', body: '24/7 multilingual triage, ticket resolution, and escalation to human agents.' },
  { icon: Workflow, title: 'Agent orchestration', body: 'Chain specialized agents into end-to-end business processes via the Command Center.' },
  { icon: LineChart, title: 'Reporting & analytics', body: 'Scheduled research, dashboards, and executive briefings generated by AI agents.' },
];

const faqs = [
  {
    q: 'What is business automation?',
    a: 'Business automation uses software — and now autonomous AI agents — to handle repetitive workflows like data entry, lead follow-up, ticket resolution, and reporting so your team can focus on higher-value work.',
  },
  {
    q: 'How is AI-driven automation different from RPA?',
    a: 'Traditional RPA follows brittle, hard-coded scripts. D3VONN agents reason about goals, adapt to changing inputs, call APIs and MCP tools dynamically, and recover from failures without human intervention.',
  },
  {
    q: 'What industries does D3VONN support?',
    a: 'D3VONN powers automation across SaaS, e-commerce, insurance, financial services, healthcare ops, marketing agencies, and DevOps teams.',
  },
  {
    q: 'How fast can I automate a workflow?',
    a: 'Most teams ship their first production agent within an hour using marketplace templates. Custom multi-agent workflows typically launch in days, not months.',
  },
];

const BusinessAutomation: React.FC = () => {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <Helmet>
        <title>Business Automation with AI Agents | D3VONN.IO</title>
        <meta
          name="description"
          content="Automate sales, support, operations, and reporting with autonomous AI agents. D3VONN replaces brittle RPA with a multi-agent business operating system."
        />
        <link rel="canonical" href="https://d3vonn.io/business-automation" />
        <meta property="og:title" content="Business Automation with AI Agents | D3VONN.IO" />
        <meta
          property="og:description"
          content="Replace brittle RPA with autonomous AI agents. Automate sales, support, ops, and reporting end-to-end."
        />
        <meta property="og:url" content="https://d3vonn.io/business-automation" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://d3vonn.io/og-image.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Business Automation with AI Agents | D3VONN.IO" />
        <meta name="twitter:image" content="https://d3vonn.io/og-image.png" />
        <script type="application/ld+json">{JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: faqs.map(f => ({
            '@type': 'Question',
            name: f.q,
            acceptedAnswer: { '@type': 'Answer', text: f.a },
          })),
        })}</script>
        <script type="application/ld+json">{JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'BreadcrumbList',
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://d3vonn.io/' },
            { '@type': 'ListItem', position: 2, name: 'Business Automation', item: 'https://d3vonn.io/business-automation' },
          ],
        })}</script>
      </Helmet>

      <section className="relative overflow-hidden px-6 pt-24 pb-20 md:pt-32">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 opacity-60"
          style={{ background: 'radial-gradient(60% 50% at 50% 0%, rgba(112,128,255,0.25), transparent 70%)' }}
        />
        <div className="relative mx-auto max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-black/60 px-3 py-1 text-[10px] uppercase tracking-[0.25em] text-primary shadow-[0_0_18px_rgba(112,128,255,0.35)]">
            <Workflow className="h-3 w-3" /> Business Automation
          </div>
          <h1 className="mt-6 text-4xl font-bold leading-tight md:text-6xl">
            Automate your business with <span className="text-primary">autonomous AI agents</span>.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground">
            D3VONN replaces brittle RPA scripts with a multi-agent operating system. Automate sales,
            support, ops, and reporting end-to-end — and let your AI workforce run your business.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Link
              to="/app"
              className="group inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-[0_0_40px_-8px_rgba(112,128,255,0.8)] transition hover:brightness-110"
            >
              Launch D3VONN <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" />
            </Link>
            <Link
              to="/workflows"
              className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/[0.03] px-6 py-3 text-sm font-semibold text-foreground backdrop-blur-xl transition hover:border-primary/40"
            >
              Explore Workflows
            </Link>
          </div>
        </div>
      </section>

      <section className="relative px-6 py-20">
        <div className="mx-auto max-w-6xl">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold md:text-4xl">Workflows D3VONN automates today</h2>
            <p className="mt-4 text-muted-foreground">
              Every workflow runs as a coordinated team of AI agents with full observability and
              recovery.
            </p>
          </div>
          <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
            {workflows.map(({ icon: Icon, title, body }) => (
              <article
                key={title}
                className="group relative rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-xl transition-all duration-300 hover:border-primary/40 hover:-translate-y-0.5"
              >
                <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg border border-primary/30 bg-primary/10 text-primary">
                  <Icon className="h-5 w-5" />
                </div>
                <h3 className="text-lg font-semibold">{title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="relative px-6 py-20">
        <div className="mx-auto max-w-3xl">
          <h2 className="text-center text-3xl font-bold md:text-4xl">Automation FAQ</h2>
          <div className="mt-10 space-y-4">
            {faqs.map(({ q, a }) => (
              <details
                key={q}
                className="group rounded-xl border border-white/10 bg-white/[0.03] p-5 backdrop-blur-xl"
              >
                <summary className="cursor-pointer list-none text-base font-semibold text-foreground">
                  {q}
                </summary>
                <p className="mt-3 text-sm text-muted-foreground">{a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className="relative px-6 py-24">
        <div className="mx-auto max-w-3xl rounded-3xl border border-primary/30 bg-primary/5 p-10 text-center backdrop-blur-xl shadow-[0_0_60px_-10px_rgba(112,128,255,0.5)]">
          <h2 className="text-3xl font-bold md:text-4xl">Replace busywork with AI agents.</h2>
          <p className="mt-4 text-muted-foreground">Launch your first automated workflow in minutes.</p>
          <Link
            to="/app"
            className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-[0_0_40px_-8px_rgba(112,128,255,0.8)] transition hover:brightness-110"
          >
            Launch D3VONN <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default BusinessAutomation;
