apiVersion: v1
kind: Namespace
metadata:
  name: d3vonn
  labels:
    app.kubernetes.io/managed-by: argocd
    security.d3vonn.io/kyverno-enforce: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
