#!/usr/bin/env python3
"""Build, validate, and optionally publish the D3VONN call-center Vapi Squad.

The source manifest comes from the D3VONN backend. This script converts the
backend's model-facing function schemas into Vapi API Request tools so trusted
call/agent context is injected by Vapi rather than generated by the LLM.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from copy import deepcopy
from typing import Any

VAPI_API = "https://api.vapi.ai"
DEFAULT_BACKEND = "https://api.d3vonn.io"

ROUTES: dict[str, tuple[str, ...]] = {
    "front_desk": ("sales", "support", "scheduling", "billing", "retention", "human_handoff"),
    "sales": ("scheduling", "front_desk", "human_handoff"),
    "support": ("front_desk", "billing", "human_handoff"),
    "scheduling": ("sales", "front_desk", "human_handoff"),
    "billing": ("support", "retention", "human_handoff"),
    "retention": ("sales", "billing", "human_handoff"),
    "human_handoff": (),
}


def _assistant_name(member: dict[str, Any]) -> str:
    return str(member["assistant"]["name"])


def _to_api_request_tool(
    tool: dict[str, Any], *, agent_key: str, backend_url: str, credential_id: str
) -> dict[str, Any]:
    function = tool["function"]
    tool_name = function["name"]
    business_schema = deepcopy(function.get("parameters") or {"type": "object", "properties": {}})
    return {
        "type": "apiRequest",
        "name": tool_name,
        "description": function.get("description", ""),
        "method": "POST",
        "url": f"{backend_url.rstrip('/')}/api/voice/call-center/tools/{tool_name}",
        "credentialId": credential_id,
        "timeoutSeconds": 15,
        "body": {
            "type": "object",
            "properties": {
                "parameters": business_schema,
            },
            "required": ["parameters"],
            "additionalProperties": False,
        },
        "parameters": [
            {"key": "call_id", "value": "{{ call.id }}"},
            {"key": "agent", "value": agent_key},
        ],
    }


def build_deployable_squad(
    manifest: dict[str, Any], *, backend_url: str, credential_id: str
) -> dict[str, Any]:
    if not credential_id:
        raise ValueError("VAPI_CALL_CENTER_CREDENTIAL_ID is required")
    source_members = manifest.get("members")
    if not isinstance(source_members, list) or len(source_members) != 7:
        raise ValueError("Expected exactly seven call-center members")

    by_key = {str(member.get("key")): member for member in source_members}
    if set(by_key) != set(ROUTES):
        raise ValueError("Call-center member keys do not match the governed routing contract")

    members: list[dict[str, Any]] = []
    for key in ROUTES:
        source = deepcopy(by_key[key])
        assistant = source["assistant"]
        model = assistant.setdefault("model", {})
        model["tools"] = [
            _to_api_request_tool(
                tool,
                agent_key=key,
                backend_url=backend_url,
                credential_id=credential_id,
            )
            for tool in model.get("tools", [])
        ]
        destinations = []
        for destination_key in ROUTES[key]:
            destination_name = _assistant_name(by_key[destination_key])
            destinations.append(
                {
                    "type": "assistant",
                    "assistantName": destination_name,
                    "name": f"handoff_to_{destination_key}",
                    "description": f"Transfer to {destination_name} when that specialist owns the caller's intent.",
                    "message": f"I’m transferring you to {destination_name} so we can continue without restarting.",
                    "transferMode": "rolling-history",
                }
            )
        members.append({"assistant": assistant, "assistantDestinations": destinations})

    return {
        "name": str(manifest.get("name") or "D3VONN Agentic Call Center"),
        "members": members,
    }


def validate_squad(payload: dict[str, Any]) -> None:
    members = payload.get("members")
    if not isinstance(members, list) or len(members) != 7:
        raise ValueError("Deployable squad must contain seven members")
    names = [member.get("assistant", {}).get("name") for member in members]
    if len(set(names)) != 7 or any(not name for name in names):
        raise ValueError("Every squad member must have a unique assistant name")
    if not names[0].startswith("D3VONN Front Desk"):
        raise ValueError("Front Desk must be the first squad member")
    for member in members:
        for tool in member.get("assistant", {}).get("model", {}).get("tools", []):
            if tool.get("type") != "apiRequest":
                raise ValueError("Operational call-center tools must deploy as apiRequest tools")
            if not tool.get("credentialId"):
                raise ValueError("Every operational tool must use a Vapi credential")
            static = {item.get("key"): item.get("value") for item in tool.get("parameters", [])}
            if static.get("call_id") != "{{ call.id }}" or not static.get("agent"):
                raise ValueError("Every tool must inject trusted call_id and agent values")


def _request_json(url: str, *, token: str | None = None, method: str = "GET", body: dict[str, Any] | None = None) -> Any:
    headers = {"Accept": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    data = None
    if body is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(body).encode("utf-8")
    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:1000]
        raise RuntimeError(f"HTTP {exc.code} from {url}: {detail}") from exc


def publish_squad(payload: dict[str, Any], *, vapi_token: str, squad_id: str | None = None) -> dict[str, Any]:
    if not vapi_token:
        raise ValueError("VAPI_PRIVATE_KEY is required for publishing")
    if squad_id:
        return _request_json(f"{VAPI_API}/squad/{squad_id}", token=vapi_token, method="PATCH", body=payload)
    return _request_json(f"{VAPI_API}/squad", token=vapi_token, method="POST", body=payload)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest-file")
    parser.add_argument("--backend-url", default=os.getenv("D3VONN_PUBLIC_API_URL", DEFAULT_BACKEND))
    parser.add_argument("--credential-id", default=os.getenv("VAPI_CALL_CENTER_CREDENTIAL_ID", ""))
    parser.add_argument("--publish", action="store_true")
    parser.add_argument("--output", default="")
    args = parser.parse_args()

    if args.manifest_file:
        with open(args.manifest_file, "r", encoding="utf-8") as handle:
            manifest = json.load(handle)
    else:
        manifest = _request_json(f"{args.backend_url.rstrip('/')}/api/voice/call-center/squad/manifest")

    payload = build_deployable_squad(manifest, backend_url=args.backend_url, credential_id=args.credential_id)
    validate_squad(payload)

    result: dict[str, Any] = {"validated": True, "member_count": 7, "published": False}
    if args.publish:
        published = publish_squad(
            payload,
            vapi_token=os.getenv("VAPI_PRIVATE_KEY", os.getenv("VAPI_API_KEY", "")),
            squad_id=os.getenv("VAPI_CALL_CENTER_SQUAD_ID") or None,
        )
        result.update({"published": True, "squad_id": published.get("id"), "name": published.get("name")})

    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2)
    print(json.dumps(result, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
