// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp-server/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-server/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp-server/tools/list-agent-templates.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp-server/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp-server/tools/list-agent-templates.ts
var toTemplateJson = (t) => ({
  id: t.id,
  name: t.name,
  description: t.description,
  category: t.category,
  version: t.version,
  tags: t.tags ?? [],
  pricingModel: t.pricing_model,
  price: t.price ?? 0,
  downloads: t.downloads ?? 0,
  avgRating: t.avg_rating ?? 0,
  isFeatured: t.is_featured ?? false,
  isVerified: t.is_verified ?? false
});
var list_agent_templates_default = defineTool({
  name: "list_agent_templates",
  title: "List agent templates",
  description: "List published agent templates from the D3VONN.IO marketplace catalog, optionally filtered by category.",
  inputSchema: {
    category: z.string().trim().min(1).optional().describe("Filter templates by category."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of templates to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("agent_templates").select(
      "id, name, description, category, version, tags, pricing_model, price, downloads, avg_rating, is_featured, is_verified"
    ).eq("status", "published").order("downloads", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const templates = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(templates.map(toTemplateJson), null, 2) }],
      structuredContent: { templates: templates.map(toTemplateJson) }
    };
  }
});

// src/lib/mcp-server/tools/list-deployed-agents.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^4.6.5";
var toAgentJson = (a) => ({
  id: a.id,
  name: a.name,
  status: a.status,
  healthScore: a.health_score ?? null,
  lastHeartbeat: a.last_heartbeat,
  totalRuns: a.total_runs ?? 0,
  successfulRuns: a.successful_runs ?? 0,
  failedRuns: a.failed_runs ?? 0,
  createdAt: a.created_at
});
var list_deployed_agents_default = defineTool2({
  name: "list_deployed_agents",
  title: "List deployed agents",
  description: "List the signed-in user's deployed agents on D3VONN.IO with their status, health score, and run counts.",
  inputSchema: {
    status: z2.enum(["running", "stopped", "error", "paused"]).optional().describe("Filter agents by status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("deployed_agents").select(
      "id, name, status, health_score, last_heartbeat, total_runs, successful_runs, failed_runs, created_at"
    ).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const agents = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(agents.map(toAgentJson), null, 2) }],
      structuredContent: { agents: agents.map(toAgentJson) }
    };
  }
});

// src/lib/mcp-server/tools/get-deployment-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
var get_deployment_status_default = defineTool3({
  name: "get_deployment_status",
  title: "Get deployment status",
  description: "Summarize the signed-in user's D3VONN.IO fleet: agent counts by status, total runs, and average health score.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deployed_agents").select("status, health_score, total_runs, successful_runs, failed_runs");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    const byStatus = {};
    let healthSum = 0;
    let healthCount = 0;
    let totalRuns = 0;
    let successfulRuns = 0;
    let failedRuns = 0;
    for (const row of rows) {
      byStatus[row.status] = (byStatus[row.status] ?? 0) + 1;
      if (typeof row.health_score === "number") {
        healthSum += row.health_score;
        healthCount += 1;
      }
      totalRuns += row.total_runs ?? 0;
      successfulRuns += row.successful_runs ?? 0;
      failedRuns += row.failed_runs ?? 0;
    }
    const summary = {
      totalAgents: rows.length,
      byStatus,
      totalRuns,
      successfulRuns,
      failedRuns,
      averageHealthScore: healthCount > 0 ? Math.round(healthSum / healthCount * 100) / 100 : null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp-server/index.ts
var projectRef = "bqkpxdjmpbucenbppxzc";
var mcp_server_default = defineMcp({
  name: "supreme-ai-deployment-hub",
  title: "supreme-ai-deployment-hub",
  version: "0.1.0",
  instructions: "D3VONN.IO agent deployment hub. Use `list_agent_templates` to browse the marketplace catalog, `list_deployed_agents` to see the caller's deployed agents, and `get_deployment_status` for a fleet summary.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_agent_templates_default, list_deployed_agents_default, get_deployment_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_server_default, { functionName: "mcp" }));
