-- =============================================================================
-- D3VONN Cyber Command Center — Security Operations Schema
-- Migration: 20260630_d3vonn_soc.sql
-- Description: Creates tables for security events, alerts, detection rules,
--              incident tracking, and the Hermes Security Agent audit trail.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. security_events — raw ingestion table for all security-relevant events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.security_events (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    source        TEXT NOT NULL,                      -- e.g. 'd3vonn-api', 'supabase-auth', 'github'
    event_type    TEXT NOT NULL,                      -- e.g. 'auth.login_failed', 'api.rate_exceeded'
    severity      TEXT NOT NULL DEFAULT 'info'        -- info | low | medium | high | critical
        CHECK (severity IN ('info','low','medium','high','critical')),
    actor         TEXT,                               -- user email, service account, or IP
    ip            INET,                               -- source IP if available
    metadata      JSONB DEFAULT '{}'::jsonb,          -- arbitrary structured payload
    outcome       TEXT DEFAULT 'unknown'              -- success | failure | unknown
        CHECK (outcome IN ('success','failure','unknown')),
    tenant_id     UUID                               -- future: multi-tenant isolation
);

CREATE INDEX IF NOT EXISTS idx_security_events_created
    ON public.security_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_type
    ON public.security_events (event_type);
CREATE INDEX IF NOT EXISTS idx_security_events_actor
    ON public.security_events (actor);
CREATE INDEX IF NOT EXISTS idx_security_events_severity
    ON public.security_events (severity);

-- ---------------------------------------------------------------------------
-- 2. security_alerts — generated by detection rules when thresholds are met
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.security_alerts (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    rule_id       TEXT NOT NULL,                      -- detection rule identifier
    title         TEXT NOT NULL,
    description   TEXT,
    severity      TEXT NOT NULL DEFAULT 'medium'
        CHECK (severity IN ('low','medium','high','critical')),
    status        TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open','acknowledged','investigating','resolved','false_positive')),
    actor         TEXT,
    ip            INET,
    evidence      JSONB DEFAULT '[]'::jsonb,          -- array of event IDs / snippets
    resolved_at   TIMESTAMPTZ,
    resolved_by   TEXT,
    tenant_id     UUID
);

CREATE INDEX IF NOT EXISTS idx_security_alerts_status
    ON public.security_alerts (status);
CREATE INDEX IF NOT EXISTS idx_security_alerts_severity
    ON public.security_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_security_alerts_created
    ON public.security_alerts (created_at DESC);

-- ---------------------------------------------------------------------------
-- 3. detection_rules — configurable detection rule definitions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.detection_rules (
    id            TEXT PRIMARY KEY,                   -- slug e.g. 'brute_force_login'
    name          TEXT NOT NULL,
    description   TEXT,
    event_type    TEXT NOT NULL,                      -- event_type to watch
    threshold     INT NOT NULL DEFAULT 5,            -- count threshold
    window_seconds INT NOT NULL DEFAULT 300,         -- sliding window
    severity      TEXT NOT NULL DEFAULT 'high'
        CHECK (severity IN ('low','medium','high','critical')),
    enabled       BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 4. security_incidents — escalated alerts grouped into incidents
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.security_incidents (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    title         TEXT NOT NULL,
    description   TEXT,
    severity      TEXT NOT NULL DEFAULT 'high'
        CHECK (severity IN ('low','medium','high','critical')),
    status        TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open','triaging','containment','eradication','recovery','closed')),
    alert_ids     UUID[] DEFAULT '{}',               -- linked alerts
    assigned_to   TEXT,
    resolved_at   TIMESTAMPTZ,
    postmortem    TEXT,
    tenant_id     UUID
);

-- ---------------------------------------------------------------------------
-- 5. hermes_security_actions — audit trail for automated agent actions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hermes_security_actions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    alert_id      UUID REFERENCES public.security_alerts(id),
    action_type   TEXT NOT NULL,                      -- e.g. 'block_ip', 'revoke_token', 'notify'
    parameters    JSONB DEFAULT '{}'::jsonb,
    result        TEXT DEFAULT 'pending'
        CHECK (result IN ('pending','success','failure','skipped')),
    agent_version TEXT DEFAULT '0.1.0'
);

-- ---------------------------------------------------------------------------
-- 6. Seed default detection rules
-- ---------------------------------------------------------------------------
INSERT INTO public.detection_rules (id, name, description, event_type, threshold, window_seconds, severity)
VALUES
    ('brute_force_login', 'Brute Force Login', 'Detects multiple failed login attempts from the same actor within a short window.', 'auth.login_failed', 5, 300, 'high'),
    ('api_abuse', 'API Abuse / Rate Limit Exceeded', 'Detects excessive API calls indicating abuse or misconfigured clients.', 'api.rate_exceeded', 50, 60, 'high'),
    ('admin_privilege_escalation', 'Admin Privilege Change', 'Detects when a user role is elevated to admin or operator.', 'auth.role_changed', 1, 1, 'critical'),
    ('token_reuse', 'Token Reuse Detected', 'Detects a revoked or expired token being presented again.', 'auth.token_reuse', 1, 1, 'critical')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7. Row-Level Security (placeholder policies — replace with tenant-aware RLS)
-- ---------------------------------------------------------------------------
ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hermes_security_actions ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (ingestion & reads)
CREATE POLICY "service_role_full_access_events" ON public.security_events
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_role_full_access_alerts" ON public.security_alerts
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_role_full_access_incidents" ON public.security_incidents
    FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "service_role_full_access_actions" ON public.hermes_security_actions
    FOR ALL USING (auth.role() = 'service_role');

-- Authenticated users can read (placeholder — tighten with tenant_id later)
CREATE POLICY "authenticated_read_events" ON public.security_events
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "authenticated_read_alerts" ON public.security_alerts
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "authenticated_read_incidents" ON public.security_incidents
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "authenticated_read_actions" ON public.hermes_security_actions
    FOR SELECT USING (auth.role() = 'authenticated');
