// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEVONN_SUPABASE_URL = 'https://tjygexesognbkwualywq.supabase.co';

const normalizeSupabaseUrl = (value: string | undefined) => {
  if (!value) return DEVONN_SUPABASE_URL;

  const trimmed = value.trim();
  if (!trimmed) return DEVONN_SUPABASE_URL;

  const withProtocol = trimmed.startsWith('http') ? trimmed : `https://${trimmed}`;

  // Guard against a known truncated project ref that can break OAuth redirects.
  if (withProtocol.includes('ognbkwualywq.supabase.co') && !withProtocol.includes('tjygexesognbkwualywq')) {
    return DEVONN_SUPABASE_URL;
  }

  return withProtocol;
};

const SUPABASE_URL = normalizeSupabaseUrl(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_CLIENT_KEY = SUPABASE_PUBLISHABLE_KEY || 'd3vonn-public-client-unconfigured';

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[D3VONN] Supabase browser key is unavailable; authenticated Supabase features will remain unavailable.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_CLIENT_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
