apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3vonn-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d3vonn-backend
  template:
    metadata:
      labels:
        app: d3vonn-backend
    spec:
      containers:
      - name: d3vonn-backend
        image: "${BACKEND_IMAGE}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
