apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3vonn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d3vonn-frontend
  template:
    metadata:
      labels:
        app: d3vonn-frontend
    spec:
      containers:
      - name: d3vonn-frontend
        image: "${FRONTEND_IMAGE}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
